---
driver_plugin: ec2
driver_config:
  require_chef_omnibus: true
  aws_access_key_id: AKIAIBHMPZ2OF7KX7OVA
  aws_secret_access_key: <%= File.read("#{ENV['HOME']}/.aws_secret_access_key").chomp %>
  aws_ssh_key_id: jenkins_vagrant
  ssh_key: <%= ENV['HOME'] %>/.ssh/jenkins_vagrant.pem
  subnet_id: subnet-2f303240
  region: us-east-1
  availability_zone: us-east-1a
  security_group_ids:
    - sg-5664c239

platforms:
- name: ubuntu-12.04
  driver_config:
    vm:
      provision:
        - ['shell', {inline: "sudo mkdir -p /etc/bind && sudo bash -c \"echo 'forwarders { 10.0.0.2; };' > /etc/bind/named.conf.forwarders\""}]
        - ['shell', {inline: "sudo mkdir -p /var/chef && sudo ln -sf /vagrant/.chef-repo/data_bags /var/chef/data_bags"}]
- name: ubuntu-10.04
  driver_config:
    vm:
      provision:
        - ['shell', {inline: "sudo mkdir -p /etc/bind && sudo bash -c \"echo 'forwarders { 10.0.0.2; };' > /etc/bind/named.conf.forwarders\""}]
        - ['shell', {inline: "sudo mkdir -p /var/chef && sudo ln -sf /vagrant/.chef-repo/data_bags /var/chef/data_bags"}]
- name: centos-6.4
  driver_config:
    vm:
      provision:
        - ['shell', {inline: "sudo mkdir -p /etc/bind && sudo bash -c \"echo 'forwarders { 10.0.0.2; };' > /etc/bind/named.conf.forwarders\""}]
        - ['shell', {inline: "sudo mkdir -p /var/chef && sudo ln -sf /vagrant/.chef-repo/data_bags /var/chef/data_bags"}]

suites:
- name: default
  run_list: ["recipe[ec2dnsserver]"]
  data_bags_path: .chef-repo/data_bags
  encrypted_data_bag_secret_key_path: <%= ENV['HOME'] %>/.chef/encrypted_data_bag_secret
  attributes: {}
