---
driver:
  name: vagrant
  require_chef_omnibus: true
  chef_omnibus_install_options: -d /tmp/vagrant-cache/vagrant_omnibus
  customize:
    cpus: 4
    memory: 1536

provisioner:
  name: chef_zero
  encrypted_data_bag_secret_key_path: <%= ENV['HOME'] %>/.chef/encrypted_data_bag_secret
  client_rb:
    environment: test

platforms:
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
      - recipe[ec2dnsserver]
    attributes:
      ec2:
        mac: '00:00:00:00:00:00'
        network_interfaces_macs:
          '00:00:00:00:00:00':
            vpc_ipv4_cidr_block: 10.99.0.0/16
      ec2dnsserver:
        contact_email: 'hostmaster@yourdomain.local'
        slaves:
          - 4.5.6.7
        recursion_clients:
          - 192.168.19.0/24
        avoid_subnets:
          - subnet-af7dcfc4
          - subnet-817dcfea
          - subnet-b07dcfdb
          - subnet-d97dcfb2
          - subnet-681bd603
          - subnet-7a1bd611
          - subnet-741bd61f
          - subnet-461bd62d
        zones:
          vagrantup.com: {}
          testforwardzone:
            type: forward
            forward: only
            forwarders: "{ 127.0.0.1 port 8600; }"
          priv.yourdomain.local:
            ptr_zone: false
            ns_zone: vagrantup.com
            static_records:
              test-storm:
                cookbook: et_ec2dnsserver
              some-host:
                value: 1.2.3.4
                type: A
              some-other-host:
                value: foo-bar
            slaves:
              - 1.2.3.4
            vpcs:
              - vpc-1e45b27b
              - vpc-9318d5f8
          10.in-addr.arpa:
            ptr_zone: true
            suffix: priv.yourdomain.local
            ns_zone: vagrantup.com
            vpcs:
              - vpc-1e45b27b
              - vpc-9318d5f8
          test-cookbook-host.yourdomain.local:
            stub: true
            ns_zone: vagrantup.com
            static_records:
              cookbook: et_ec2dnsserver
          test-value-host.yourdomain.local:
            stub: true
            ns_zone: vagrantup.com
            static_records:
              value: 1.1.1.1
              type: A
